out_dir: results
metric_best: accuracy
num_workers: 4
wandb:
  use: True
  project: Cycle_Detection_GatedGCN
  entity: miw039-uc-san-diego
dataset:
  format: PyG-SimpleGraphML  # Use the simple GraphML loader
  name: cycle_detection
  task: graph
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: LinearNode+RWSE  # Will handle graphs without node features
  node_encoder_bn: False
  edge_encoder: True  # No edge features
  edge_encoder_name: DummyEdge
  edge_encoder_bn: False
data_src:
  graphml_dir: /home/miw039/private/dsc180/graph_token_outputs/graphs/
  label_dir: /home/miw039/private/dsc180/graph_token_outputs/cycle_check_labels/
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,17)
  model: Linear
  dim_pe: 20
  raw_norm_type: BatchNorm

train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 50
model:
  type: custom_gnn
  loss_fun: cross_entropy  # Binary classification for cycle/no-cycle
  edge_decoding: dot
  graph_pooling: mean
 
gnn:
  layers_pre_mp: 0
  layers_mp: 3
  layers_post_mp: 1
  dim_inner: 64
  batchnorm: False
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
  layer_type: gatedgcnconv
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.001
  max_epoch: 50
  scheduler: reduce_on_plateau
  num_warmup_epochs: 10
  reduce_factor: 0.5
  schedule_patience: 5
  min_lr: 1e-6